INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatCat', 'Viande de Chat', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatLDog', 'Viande de Grand Rottweiler', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatWestie', 'Viande de Westie', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatCaniche', 'Viande de Caniche', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatGR', 'Viande de Golden Retriever', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatRott', 'Viande de Rottweiler', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatShep', 'Viande de Shepherd', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatHusky', 'Viande de Husky', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatCarlin', 'Viande de Carlin', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatBC', 'Viande de Border Collie', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatCow', 'Viande de Vache', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatRabbit', 'Viande de Lapin', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatPuma', 'Viande de Puma', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatChicken', 'Viande de Volaille', 10, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('MeatCerf', 'Viande de Cerf', 10, 0, 1);